### ISSUE TITLE
Can't get the constant EBAY_US

### ISSUE THREAD

**Issue by paulcookie** [ccollins/rebay#1]
NoMethodError: undefined method `EBAY_US' for Rebay::Api:Class

after

> > shopping = Rebay::Shopping.new
> > shopping.get_category_info({:categoryId => '1'})

**Comment by ccollins** [comment]
I'll check it out soon.   I just realized that I took the work in progress out of the readme prematurely :)  I've been developing this wrapper for a project Im working on and havent tested sufficiently with live data.

**Comment by paulcookie** [comment]
Hope so))

i relly need this plugin in my rails project...

**Comment by ccollins** [comment]
What particular functionality are you looking for?  I plan on finishing this up friday/sat, but its just for the finding api and just enough of the shopping api to get category information.  If you need more then that, I'm not sure this will provide it.

**Comment by paulcookie** [comment]
so sad... i need some light and quick plugin for ebay shopping and i like yours becouse it's work on JSON
and now i think i'm switch to ebayapi by codyfauser (but it needs to fix some bugs) and use it
sorry that you're not going to expand the IPA, I think poluchlos would be very cool

**Comment by ccollins** [comment]
Yeah, it may not fit your needs.  I'll continue to work and expand on it, but those are my goals for the near future.  Watch the project for updates, I may get them in sooner rather then later.

**Comment by paulcookie** [comment]
Ok, and thank you for your quick reply ...
I'll watch for updates

**Comment by ccollins** [comment]
I've got what I consider a 1.0 alpha release.  I haven't tested the code yet with real-world examples (that will probably come within the next week).  You are welcome to try it out.  I'll do my best to get to the fixes quick if you encounter any bugs.

**Comment by paulcookie** [comment]
I will))
