### ISSUE TITLE
DEPRECATION WARNING: railtie_name is deprecated and has no effect.

### ISSUE THREAD

**Issue by zevarito** [ccollins/rebay#2]
I just want to let you know that rebay drops that message with rails 3.
Avoid it should be as simple as remove the call.

Thanks!

**Comment by ccollins** [comment]
Awesome, thanks for letting me know.  I'll get that fixed this week.

**Comment by ccollins** [comment]
This should be fixed in master.  I need a bit more work before I can release the next version, however.
