### ISSUE TITLE
Do you need dev_id and cert_id also?

### ISSUE THREAD

**Issue by debugging** [ccollins/rebay#3]
I added an initliazer and set it with my application id.

When making a simple call:

`finder = Rebay::Finding.new
response = finder.get_search_keywords_recommendation({:keywords => 'acordian'})`

I am getting the error:

```
#<Rebay::Response:0x102d39598 @response={"errorMessage"=>{"error"=>{"parameter"=>{"@name"=>"Param1", "__value__"=>"Invalid Application: xxxxxxx"}, "category"=>"System", "errorId"=>"11002", "domain"=>"Security", "subdomain"=>"Authentication", "severity"=>"Error", "message"=>"Authentication failed : Invalid Application: xxxxxxx"}}}> 
```

(xxx is my app_id)

Little confused why I would be getting this?  My app_id is setup correctly I would think.  Does anything look wrong?

**Comment by ccollins** [comment]
Im sorry about being an absentee landlord here.  I remember looking at making the calls to the new api and the app id was required.  

When debugging this, I used the example requests from ebay and put them directly to my browser.

Take a look at this part of the ebay docs:
https://skitch.com/chuckcollins/fqjg7/getsearchkeywordsrecommendation-call-reference-ebay-finding-api
http://developer.ebay.com/DevZone/finding/CallRef/getSearchKeywordsRecommendation.html

Make the same request with your own app id and let me know the result.

If its an issue with rebay, I'll get it sorted asap.

**Comment by ericmeyer** [comment]
I too am running into this same issue.  Based on my understanding of the documentation, I would expect you need some sort of token or additional id passed in.

Code:

``` ruby
Rebay::Api.configure do |rebay|
    rebay.app_id = APP_ID
end

finder = Rebay::Finding.new
response = finder.get_search_keywords_recommendation({:keywords => 'acordian'})

puts response.inspect
```

Output:

#<Rebay::Response:0x00000100852540 @response={"errorMessage"=>{"error"=>{"errorId"=>"11002", "domain"=>"Security", "severity"=>"Error", "category"=>"System", "message"=>"Authentication failed : Invalid Application: xxxxx", "subdomain"=>"Authentication", "parameter"=>{"@name"=>"Param1", "**value**"=>"Invalid Application: xxxxxx"}}}}>

**Comment by ericmeyer** [comment]
Apparently it was because i was using a sandbox app id.  This problem went away once I started using a production app id

**Comment by ccollins** [comment]
I ran into the exact same issue.  You need to use your actual application id for these newer api's.  I'll make an update to the readme to make others aware of this.
